# Generated by Django 3.0.1 on 2019-12-22 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 22, 12, 8, 49, 429569), verbose_name='date published'),
        ),
    ]
