# Generated by Django 3.0.1 on 2019-12-22 12:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191222_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 22, 12, 10, 4, 62424, tzinfo=utc), verbose_name='date published'),
        ),
    ]
